spring:
  application:
    name: reflecta_backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8000

jwt:
  access:
    secret: ${ACCESS_SECRET}
    expiration-time: ${ACCESS_EXPIRATION_TIME}
  refresh:
    secret: ${REFRESH_SECRET}
    expiration-time: ${REFRESH_EXPIRATION_TIME}